package com.craftinginterpreters.meowbasic;

public enum TokenType {
	// single-character tokens
	LEFT_PAREN, RIGHT_PAREN, COMMA, DOT, COLON, STAR, BACK_SLASH, PERCENT, CARET,
	
	// two character tokens
	AND_AND, PIPE_PIPE,
	
	// one or two character tokens
	SLASH, SLASH_SLASH, BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, PLUS, PLUS_PLUS, MINUS, MINUS_MINUS, 
	
	// literals
	IDENTIFIER, CHARACTER, SHORT_INTEGER, INTEGER, LONG_INTEGER, SINGLE_FLOAT, DOUBLE_FLOAT, STRING_TYPE, BOOLEAN,
	
	// keywords
	BOOL, CASE, CHAR, DEFAULT, DO, DOUBLE, EACH, ELSE, END, FALSE, FOR, FUN, IF, IN, INT, LONG, LOOP, NEXT, NULL, PRINT, REM, RETURN, SELECT, SHORT, SINGLE, STRING, SUB, TO, TRUE, UNTIL, VAR, WHILE,
	
	EOF

	
}
