package com.craftinginterpreters.meowbasic;

public enum TokenType {
	// single-character tokens
	LEFT_PAREN, RIGHT_PAREN, COMMA, DOT, COLON, STAR, BACK_SLASH, PERCENT, CARET, NEW_LINE,
	
	// two character tokens
	AND_AND, PIPE_PIPE,
	
	// one or two character tokens
	SLASH, SLASH_SLASH, BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, PLUS, PLUS_PLUS, MINUS, MINUS_MINUS, 
	
	// literals
	ANY, IDENTIFIER, CHARACTER, INTEGER, FLOAT, STRING, BOOLEAN,
	
	// keywords
	CASE, DEFAULT, DIM, DO, EACH, ELSE, ENDIF, ENDFUN, ENDSEL, ENDSUB, FALSE, FOR, FUN, IF, IN, LOOP, NEXT, NULL, PRINT, REM, RETURN, SELECT, SUB, THEN, TO, TRUE, UNTIL, VAR, WHILE,
	
	EOF

	
}
